[package]
name = "protobuf"
version = "0.1.0"
description = "A motoko library for encoding protobuf messages"
repository = "https://github.com/edjcase/motoko_protobuf"
keywords = ["protobuf", "encode", "serialization"]
license = "MIT"

[dependencies]
"xtended-iter@1" = "1.1.0"
"leb128@1" = "1.1.0"
"xtended-numbers@2" = "2.1.0"
"core@1" = "1.0.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
